### ISSUE TITLE
Unprivileged ping on Linux

### ISSUE THREAD

**Issue by thewh1teagle** [hankbao/ping-async#1]
Is there any way to ping with icmp or similar method without being root on Linux (and without setting sysctl)? if it's not already supported, can we add it?

**Comment by hankbao** [comment]
As far as I know, the only way to ping is to use the ping command if you aren't root and don't have the sysctl flag set.

**Comment by thewh1teagle** [comment]
@hankbao 
Thanks for reply :)

Eventually I used this crate: [pinger](https://github.com/orf/gping/tree/master/pinger)
I'm not sure how, but it works without admin rights on macOS / Windows / Linux

**Comment by hankbao** [comment]
> Eventually I used this crate: [pinger](https://github.com/orf/gping/tree/master/pinger) I'm not sure how, but it works without admin rights on macOS / Windows / Linux

They invoke the ping command and parse the output. If that works for you, then it's a good choice.
